In [ ]:
from Brands import Sonites
from Analyzer import Analyzer
from Solver import Solver
import numpy as np

son = Sonites()
print("----")
an = Analyzer()
print("----")
solver = Solver()



./Exports/TeamExport_A46051_Alpha_M_Period 3.xlsx loaded
No weights provided
./Exports/TeamExport_A46051_Alpha_M_Period 3.xlsx loaded
./Exports/TeamExport_A46051_Alpha_M_Period 3.xlsx loaded
Attributes file:./Attributes/attributes_3.json


In [2]:
df_seg_sem_fc = an.forecast_df(dataframe=son.df_segments_semantic, steps=2)
target_sem = df_seg_sem_fc[(df_seg_sem_fc["Segment"]=="Explorers")&(df_seg_sem_fc["Period"]==5)][['# Features', 'Design Index', 'Battery Life', 'Display Size', 'Proc. Power', 'Price']].values
target_sem

array([[4.489999999999991, 2.7399999999999896, 5.42999999999998,
        5.489999999999952, 5.909999999999947, 4.39999999999999]],
      dtype=object)

In [3]:
df_seg_mds_fc = an.forecast_df(dataframe=son.df_segments_mds, steps=2)
target_mds = df_seg_mds_fc[(df_seg_mds_fc["Segment"]=="Explorers")&(df_seg_mds_fc["Period"]==5)][['Economy', 'Performance', 'Convenience']].values
target_mds


array([[-2.9, 12.199999999999974, -3.8200000000000056]], dtype=object)

In [17]:
optimum = solver.find_optimum(ideal_semantic=target_sem, ideal_mds=target_mds, semantic_weights=son.rel_importance_features, 
                              mds_weights=[1/3,1/3,1/3], error_weights=np.array([2,1]))

Optimal Features: [ 13.7771045    5.40882125  75.13004054  31.43472095  90.23523662
 360.64020121]
Minimum Combined Error: 0.05101430300072011


In [5]:
sem_solved  = solver.regress_semantic(optimum[0])
sem_solved

[4.794708791480178,
 2.888235772459064,
 5.1642643670272195,
 5.548093557783089,
 6.025823656001767,
 4.369597261503873]

In [6]:
target_sem

array([[4.489999999999991, 2.7399999999999896, 5.42999999999998,
        5.489999999999952, 5.909999999999947, 4.39999999999999]],
      dtype=object)

In [7]:
from Utils import relevance_score

relevance_score(sem_solved, target_sem, max_distance_1D=6, weights=an.rel_importance_features)

0.97890962534491

In [8]:
mds_solved = solver.regress_mds(optimum[0])
mds_solved

[-3.6757694719960696, 9.417509333539119, -4.865777398680255]

In [9]:
target_mds

array([[-2.9, 12.199999999999974, -3.8200000000000056]], dtype=object)

In [10]:
relevance_score(mds_solved, target_mds, max_distance_1D=40, weights=[1/3, 1/3, 1/3])

0.9556582332186184

In [11]:
son.move_features

# Features  Design Index  Battery Life  Display Size  \
MARKET : Sonites                                                         
MOVE                      13             6            82            31   

                  Proc. Power  Rec. retail price  Base Cost  
MARKET : Sonites                                             
MOVE                       83                350        158