In [ ]:
from Scraper import Scraper
import numpy as np

scraper = Scraper()

inputs = np.array([[1,2,3,4,5,6],
                   [6,5,4,3,2,1]])


res = scraper.run_regression_semantic(inputs)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
---------- Logged In ----------
---------- Accessed Regression Page ----------
[1 2 3 4 5 6]
1.0
2.0
3.0
4.0
5.0
6.0
[6 5 4 3 2 1]
6.0
5.0
4.0
3.0
2.0
1.0


In [3]:
res [1]

newAttValue_1 newAttValue_2 newAttValue_3 newAttValue_4 newAttValue_5  \
0             5             5            49            22            74   
1            18             8            60            16            21   

  newAttValue_6  
0           468  
1           133